'use strict';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d'),W=PatriotasWorld;
const pictures={},crops={patriota1:[192,458,338,438],patriota2:[223,437,314,465],lula:[423,15,378,506],bolsonaro:[73,23,196,271]};
let hero='patriota1',world=W.create(),mode='menu',last=0,camera=0,muted=true,audioContext,frame=0;
const input={left:false,right:false,jump:false},held=new Set();
function tone(f=440,d=.08){if(muted)return;try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();audioContext.resume();const o=audioContext.createOscillator(),g=audioContext.createGain();o.type='square';o.frequency.value=f;g.gain.setValueAtTime(.035,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+d);o.connect(g);g.connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+d);}catch{}}
Promise.all(Object.entries({patriota1:'patriota1.jpeg',patriota2:'patriota2.jpeg',lula:'lula.webp',bolsonaro:'bolsonaro.webp',pt:'pt.png'}).map(([key,file])=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{pictures[key]=im;resolve();};im.onerror=()=>reject(Error(file));im.src='assets/'+file;}))).then(()=>{$('start').disabled=false;$('start').textContent='INICIAR MISSÃO →';}).catch(()=>{$('loadError').textContent='Não foi possível carregar as imagens. Confira a pasta assets e recarregue.';});
function clearInput(){held.clear();input.left=input.right=input.jump=false;}
function start(){world=W.create();camera=0;mode='playing';clearInput();['menu','result','paused'].forEach(id=>$(id).classList.add('hidden'));$('pause').disabled=false;$('heroLabel').textContent=hero==='patriota1'?'PATRIOTA 1':'PATRIOTA 2';tone(523,.12);}
function menu(){mode='menu';clearInput();$('menu').classList.remove('hidden');$('result').classList.add('hidden');$('paused').classList.add('hidden');$('pause').disabled=true;}
function pause(){if(mode==='playing'){mode='paused';clearInput();$('paused').classList.remove('hidden');}else if(mode==='paused'){mode='playing';$('paused').classList.add('hidden');}}
function finish(){mode=world.state;$('pause').disabled=true;clearInput();const won=mode==='won';$('resultTag').textContent=won?'MISSÃO CUMPRIDA':'FIM DE JOGO';$('resultTitle').textContent=won?'Você chegou à bandeira!':'Vamos tentar de novo?';$('resultText').textContent=won?`${hero==='patriota1'?'Patriota 1':'Patriota 2'} foi recebido por Bolsonaro na chegada.\n${world.score} estrelas · ${timeText(world.time)} · ${world.lives} vida(s)`:`Os obstáculos levaram suas três vidas.\nVocê coletou ${world.score} estrelas. A missão continua!`;$('result').classList.remove('hidden');tone(won?784:180,.3);if(won){try{const key='super-patriotas-recorde';const prev=JSON.parse(localStorage.getItem(key)||'null');if(!prev||world.time<prev.time)localStorage.setItem(key,JSON.stringify({hero,time:world.time,score:world.score}));}catch{}}}
document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{hero=b.dataset.hero;document.querySelectorAll('.choice').forEach(el=>{const selected=el===b;el.classList.toggle('selected',selected);el.setAttribute('aria-pressed',selected);});tone(400,.05);});
$('start').onclick=start;$('retry').onclick=start;$('choose').onclick=menu;$('pauseChoose').onclick=menu;$('pause').onclick=pause;$('resume').onclick=pause;$('sound').onclick=()=>{muted=!muted;$('sound').textContent='Som: '+(muted?'OFF':'ON');tone();};
const bindings={ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right',Space:'jump',ArrowUp:'jump',KeyW:'jump'};
function sync(){input.left=[...held].some(k=>k==='left'||bindings[k]==='left');input.right=[...held].some(k=>k==='right'||bindings[k]==='right');}
document.addEventListener('keydown',e=>{if(e.code==='KeyP'||e.code==='Escape'){if(!e.repeat)pause();return;}if(!bindings[e.code]||mode!=='playing')return;e.preventDefault();if(bindings[e.code]==='jump'&&!held.has(e.code))input.jump=true;held.add(e.code);sync();});
document.addEventListener('keyup',e=>{held.delete(e.code);sync();});
document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();if(mode!=='playing')return;b.setPointerCapture(e.pointerId);held.add(b.dataset.key);if(b.dataset.key==='jump')input.jump=true;sync();};const release=()=>{held.delete(b.dataset.key);sync();};b.onpointerup=release;b.onpointercancel=release;b.onlostpointercapture=release;});
window.addEventListener('blur',()=>{clearInput();if(mode==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='playing')pause();});
function timeText(t){return String(Math.floor(t/60)).padStart(2,'0')+':'+String(Math.floor(t%60)).padStart(2,'0');}
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(x,y,w,h);}function ellipse(x,y,rx,ry,c){ctx.fillStyle=c;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();}function text(t,x,y,size=14,color='#153d32'){ctx.fillStyle=color;ctx.font=`800 ${size}px system-ui`;ctx.fillText(t,x,y);}
function star(x,y,r,color){ctx.fillStyle=color;ctx.beginPath();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,rr=i%2?r*.45:r;const xx=x+Math.cos(a)*rr,yy=y+Math.sin(a)*rr;if(!i)ctx.moveTo(xx,yy);else ctx.lineTo(xx,yy);}ctx.closePath();ctx.fill();}
function face(key,x,y,w,h){if(!pictures[key])return;ctx.save();ctx.beginPath();ctx.ellipse(x+w/2,y+h/2,w/2,h/2,0,0,Math.PI*2);ctx.clip();ctx.drawImage(pictures[key],...crops[key],x,y,w,h);ctx.restore();}
function brazil(x,y,w,h){rect(x,y,w,h,'#18964b');ctx.fillStyle='#ffe451';ctx.beginPath();ctx.moveTo(x+w/2,y+5);ctx.lineTo(x+w-5,y+h/2);ctx.lineTo(x+w/2,y+h-5);ctx.lineTo(x+5,y+h/2);ctx.closePath();ctx.fill();ellipse(x+w/2,y+h/2,w*.18,h*.27,'#174a92');ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x+w*.34,y+h*.44);ctx.lineTo(x+w*.66,y+h*.56);ctx.stroke();}
function character(key,x,y,scale=1,walking=false,facing=1){ctx.save();ctx.translate(x+19*scale,y);ctx.scale(scale*facing,scale);const swing=walking?Math.sin(frame*12)*5:0;ellipse(0,72,24,5,'#05251930');rect(-13,44,26,19,key==='lula'?'#44464e':key==='bolsonaro'?'#202c37':key==='patriota1'?'#ffe05a':'#269e55');rect(-12,60+swing,10,12,'#193f75');rect(2,60-swing,10,12,'#193f75');rect(-14,69+swing,14,5,'#263642');rect(1,69-swing,14,5,'#263642');rect(-19,46-swing,6,16,'#d4a177');rect(13,46+swing,6,16,'#d4a177');face(key,-24,-6,48,54);if(key==='lula'){rect(-2,45,5,12,'#bf3936');}ctx.restore();}
function cloud(x,y,s){ellipse(x,y,40*s,15*s,'#ffffffbb');ellipse(x-18*s,y-8*s,22*s,20*s,'#ffffffbb');ellipse(x+16*s,y-12*s,23*s,24*s,'#ffffffbb');}
function draw(){const grad=ctx.createLinearGradient(0,0,0,540);grad.addColorStop(0,'#83d3e9');grad.addColorStop(1,'#ddf5cc');ctx.fillStyle=grad;ctx.fillRect(0,0,960,540);ellipse(817-camera*.08,83,35,35,'#ffea8c');for(let i=0;i<9;i++)cloud(i*220+70-camera*.18,65+(i%3)*32,.8);for(let i=0;i<14;i++){let x=i*270-camera*.3;ellipse(x,455,220,120,'#90c49b');ellipse(x+60,475,160,80,'#64a789');}ctx.save();ctx.translate(-camera,0);
for(const p of world.platforms){rect(p.x,p.y,p.w,p.h,p.ground?'#b68752':'#b49361');rect(p.x,p.y,p.w,9,'#356f3c');rect(p.x,p.y+9,p.w,5,'#6dae50');ctx.fillStyle='#8d6840';for(let x=p.x+8;x<p.x+p.w;x+=34){ctx.fillRect(x,p.y+28,19,5);if(p.ground)ctx.fillRect(x+12,p.y+57,10,5);}if(!p.ground)rect(p.x,p.y+p.h-4,p.w,4,'#765a37');}
for(const cp of [2040,4130]){rect(cp+15,370,5,80,'#fbf0cc');brazil(cp+20,375,44,29);text('RETORNO',cp-9,363,10);}
for(const s of world.stars)if(!s.taken){ellipse(s.x+10,s.y+12,15,15,'#fff2a150');star(s.x+10,s.y+10+Math.sin(frame*3+s.x)*3,12,'#f0bc31');star(s.x+10,s.y+9+Math.sin(frame*3+s.x)*3,8,'#ffe779');}
for(const gem of world.jewels)if(!gem.taken){const x=gem.x+13,y=gem.y+15+Math.sin(frame*4+gem.x)*4;ellipse(x,y,25,25,'#b4ffff55');ctx.fillStyle='#4ae8ee';ctx.strokeStyle='#fff8d8';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x-13,y-5);ctx.lineTo(x-7,y-13);ctx.lineTo(x+7,y-13);ctx.lineTo(x+13,y-5);ctx.lineTo(x,y+15);ctx.closePath();ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(x-13,y-5);ctx.lineTo(x+13,y-5);ctx.moveTo(x-7,y-13);ctx.lineTo(x,y+15);ctx.lineTo(x+7,y-13);ctx.stroke();text('JOIA',x-14,y-23,10,'#164c47');}
for(const f of world.flags){rect(f.x+2,f.y,4,f.h,'#71533b');if(pictures.pt)ctx.drawImage(pictures.pt,f.x+5,f.y,46,31);rect(f.x-3,GROUND-5,15,5,'#4e4436');}
for(const e of world.enemies)if(e.alive)character('lula',e.x,e.y,1,true,e.dir);
rect(5050,242,6,208,'#fbf6d5');brazil(5056,249,102,68);ellipse(5053,238,7,7,'#ffd254');character('bolsonaro',5010,GROUND-96,1.3,false);text('CHEGADA',4917,338,19);rect(4910,348,99,4,'#e3be51');
const p=world.player;if(p.invincible===0||Math.floor(frame*12)%2)character(hero,p.x,p.y,p.big?1.5:1,Math.abs(p.vx)>0&&p.grounded,p.facing);
if(mode==='won')for(let i=0;i<60;i++){const x=4900+(i*37)%290,y=(frame*70+i*51)%460;rect(x,y,5,9,i%2?'#ffdc54':'#189a57');}ctx.restore();
rect(20,515,920,5,'#183d3425');rect(20,515,920*Math.min(1,p.x/4940),5,'#f3c743');if(world.notice>0){const m=world.message;ctx.font='bold 16px system-ui';const mw=ctx.measureText(m).width;rect(480-mw/2-16,22,mw+32,35,'#133c31dc');text(m,480-mw/2,45,16,'#ffdf54');}
}
function loop(now){let dt=Math.min((now-last)/1000||0,1/20);last=now;frame+=dt;if(mode==='playing'){const previous=world.score,previousGems=world.jewelsCollected,jumps=world.player.jumps;if(input.jump&&jumps<2)tone(580,.07);while(dt>0){const slice=Math.min(dt,1/120);W.step(world,input,slice);dt-=slice;}if(world.score>previous)tone(900,.06);if(world.jewelsCollected>previousGems)tone(1100,.25);if(world.state!=='playing')finish();}camera=Math.max(0,Math.min(W.WIDTH-960,world.player.x-280));draw();$('heroLabel').textContent=(hero==='patriota1'?'PATRIOTA 1':'PATRIOTA 2')+(world.player.big?' · SUPER':'');$('coins').textContent='★ '+String(world.score).padStart(2,'0');$('lives').textContent='♥ '.repeat(world.lives)+'♡ '.repeat(3-world.lives);$('timer').textContent=timeText(world.time);requestAnimationFrame(loop);}requestAnimationFrame(loop);
